<%@ Page Title="" Language="C#" MasterPageFile="~/PRAMaster.Master" AutoEventWireup="true" CodeBehind="EditUsers.aspx.cs" Inherits="PRAHRM2.EditUsers" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div id="placeHolderDiv" class="container-div" runat="server">

        <br />
        <br />
        <br />

        <b> 
            &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
            &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
            &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
            &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
            Edit Users
        </b>

        &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
        &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
        &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
        &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
        
        <asp:Button id="buttons" runat="server" Text="Cancel" CssClass="buttons" OnClick="cancel"/>

        <br />
        <br />
        <br />

        Search for users via first name:- <br />
        <asp:TextBox ID="searchresult" CssClass="textboxes" runat="server"></asp:TextBox> <br /> <br />
        <asp:Button id="searchbutton" CssClass="buttons" Text="Search" runat="server" OnClick="searchUsers"/>

        <br />
        <br />
        <br />

        <asp:GridView
            ID="userEditGrid"
            runat="server"
            AutoGenerateEditButton="true"
            AutoGenerateDeleteButton="true"
            AutoGenerateColumns="true"
            EnableViewState="false"
            OnRowEditing="editUserRow"
            CssClass="mydatagrid"
            HeaderStyle-CssClass="header"
            EditRowStyle-CssClass="selectedrow"
            RowStyle-CssClass="rows"
            OnRowCancelingEdit="cancelEditing"
            type="button"
            OnRowDeleting="deleteUserRow"
            OnRowUpdating="updateUserRow"
            DataKeyNames="userID"
            ></asp:GridView>

        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
            
        © 2017 - Punjab Revenue Authority

        <br />
        <br />
        <br />
        <br />
        <br />
        <br />

    </div>

</asp:Content>
